@extends('layouts.main')

@section('container')
    <h1>Home</h1>

    <div class="mt-4 fs-5">
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatibus cumque soluta magnam fuga temporibus fugiat nam ex nulla ipsa necessitatibus sapiente ullam deserunt unde voluptates laudantium architecto beatae at voluptatem, cum repudiandae atque ut. Asperiores, quos provident illum minus nisi consequuntur atque totam iure modi, nihil nesciunt eaque quisquam ad, rem aperiam voluptates maiores doloribus voluptatum vero. Accusantium fugiat eaque, totam quidem maxime quasi quisquam aliquid est cupiditate, esse dicta eligendi qui magnam delectus doloremque enim sed voluptas? Ex, soluta provident cumque quos delectus iusto adipisci expedita culpa possimus explicabo sit eveniet iure et rem. Sint itaque totam non perspiciatis!</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque ipsam fugit impedit minus ipsum necessitatibus est, atque praesentium unde eaque reiciendis odio nam ea! Saepe ab optio modi excepturi corporis dolore quidem, fuga cum, quam dicta nam expedita quisquam esse, reprehenderit rerum? Soluta consequatur praesentium, sint in optio tenetur a, repellat, temporibus libero possimus eligendi fugiat earum voluptatibus itaque. Ea vitae commodi itaque corrupti natus, autem doloremque ratione alias quam obcaecati provident possimus! Id optio dolorum deleniti mollitia voluptates, explicabo nihil quisquam debitis, placeat odio nesciunt totam, nostrum pariatur quos? Laboriosam obcaecati quisquam est ipsa neque esse, voluptatum adipisci officiis voluptate ut praesentium asperiores reprehenderit nostrum doloribus facilis, atque minima enim ducimus eligendi ex sunt sed amet maxime pariatur? Illo!</p>
        <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tenetur accusantium eum ducimus aliquid! Ab sequi voluptates distinctio expedita mollitia atque sapiente quidem, quos praesentium modi, delectus nisi tenetur fugit minima id ea? At vero libero, possimus quia ab asperiores maiores aliquid sit animi error ducimus fuga earum corporis veritatis impedit debitis. Porro illum nesciunt voluptatibus ipsam magnam, odit excepturi aut earum harum ut voluptas ab accusantium hic minus perspiciatis fuga eius itaque nulla voluptatem enim suscipit! Odio dolorem quia dolore nobis praesentium, officiis culpa itaque iste in adipisci, deleniti architecto ea officia! Aperiam molestiae cumque accusamus assumenda pariatur maiores cum placeat doloremque, alias hic maxime obcaecati omnis. Sint deserunt unde maiores, sed numquam facere vero, rerum ullam placeat eaque nobis aspernatur corrupti ex similique eos laborum earum nisi quibusdam architecto! Cum atque aperiam repellendus iste. Fuga eligendi at itaque obcaecati temporibus eius facere ipsum quod atque inventore aut distinctio excepturi, est placeat. Voluptatibus dolores voluptate aperiam tenetur perferendis quia mollitia tempore non dolore, animi ex earum facere accusamus cumque, quasi excepturi itaque aspernatur doloribus ipsa. Libero quibusdam vero doloribus necessitatibus veritatis commodi nesciunt, sit quos minima laborum repellat, quae culpa aut corrupti pariatur quaerat? Ab nostrum animi expedita sed laudantium?</p>
        <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Excepturi voluptatum optio corporis sint nihil expedita repellat fugit architecto repudiandae, culpa commodi dicta amet pariatur, accusantium, vitae iste in. Earum eos aliquid ab consequatur temporibus in sit, aut dolore quod nesciunt velit maiores cumque modi ea! Perspiciatis iste itaque laboriosam necessitatibus optio, vero mollitia rem esse cumque, corrupti illo! Tempora dolore ullam aliquid sit voluptates est minima voluptatem consequatur quibusdam obcaecati. Illum deleniti enim nisi tempore id possimus, eos a quae cupiditate sed vel velit, aut dignissimos facere quia cumque inventore veniam repellendus assumenda autem voluptas sapiente magni sequi animi. Deleniti modi, iure officiis voluptatibus dignissimos in dolore, reiciendis quas vel quod eligendi quia ut asperiores totam placeat esse explicabo similique temporibus facere. Eaque delectus optio quia quae dolores animi sunt id exercitationem, vitae odio, hic veniam illo. Voluptatum numquam sunt assumenda ab. Maxime deleniti quibusdam excepturi? Impedit aliquam, commodi minima optio sunt aspernatur temporibus odio rerum, similique nostrum recusandae facere voluptatibus dolores suscipit non voluptates amet ipsam possimus atque. Facere, cumque quod dolor beatae perspiciatis id numquam voluptatum consequuntur suscipit?</p>
        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nam id saepe laborum! Voluptas nihil laboriosam veniam, omnis alias corporis sapiente in sint minus sequi sed cupiditate perferendis aut id aliquid eaque ducimus cum pariatur. Delectus harum vero error, laboriosam veritatis sequi? Quibusdam, culpa a distinctio, at sequi libero mollitia, accusantium architecto molestias maiores totam deserunt nulla ullam tempora! Quam ad cupiditate totam obcaecati quas quae nihil hic repudiandae eveniet quos mollitia velit pariatur tenetur minus itaque vel modi dolores, voluptate assumenda rerum ea inventore eligendi quod tempore? Voluptatum, rem reprehenderit.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore, similique repudiandae! Sed commodi explicabo repudiandae voluptatem dolorem deserunt nobis, unde praesentium, neque tempore, illo doloremque earum error repellat laboriosam at perferendis impedit odit! Necessitatibus earum, sunt facilis accusamus autem nobis voluptates, quam aliquam laudantium quidem dolores rem? Tenetur illo libero ut quo corrupti suscipit porro aspernatur distinctio. Tenetur similique sapiente amet placeat assumenda sit repellendus in excepturi quia eos. Iure mollitia reiciendis blanditiis laborum officiis, earum eveniet laudantium, facere tenetur commodi voluptas magnam laboriosam? Itaque, culpa. Deserunt et nemo, consequuntur vel, nihil numquam at eveniet non earum, distinctio vitae ad architecto eius consectetur omnis doloribus. Id obcaecati repellendus, laboriosam illum, aut nisi placeat quas mollitia vel maxime inventore omnis necessitatibus! Omnis at officia corporis ullam maxime distinctio a perspiciatis ipsam odio ex consequatur labore architecto doloremque provident, itaque illo deleniti natus, qui beatae maiores deserunt! Saepe nostrum iure aliquam eius earum perspiciatis consequuntur quasi, a, obcaecati laborum maxime rerum ipsam!</p>
    </div>
@endsection